# Yarn configuration for cross-platform compatibility
# This ensures esbuild works on both Windows (development) and Linux (Vercel deployment)

supportedArchitectures:
  os: ["win32", "linux", "darwin"]
  cpu: ["x64", "arm64"]
  libc: ["glibc", "musl"]

# Cache configuration
cacheFolder: "./.yarn/cache"

# Node modules linker
nodeLinker: "node-modules"

# Enable global cache
enableGlobalCache: false

# Compression level for better performance
compressionLevel: 0