# Yarn configuration for cross-platform compatibility
supportedArchitectures:
  os: ["linux", "win32", "darwin"]
  cpu: ["x64", "arm64"]
  libc: ["glibc", "musl"]

# Enable strict engine checking
engineStrict: true

# Use node-modules linker for better compatibility
nodeLinker: node-modules